springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true

    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /
        disable-swagger-default-url: true

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus, health
            base-path: '/'
            path-mapping:
                prometheus: 'metrics'